### ISSUE TITLE
configurable messags

### ISSUE THREAD

**Issue by madtomic** [dyukusi/Bukkit_plugins#1]
Make all messages configurable via config.yml

**Comment by dyukusi** [comment]
I'll upload new version that includes except this option because I guess this option will take time.

Please wait for a while.

**Comment by madtomic** [comment]
Grammar Change:

When player is trying to shift click craft.

Change <Sorry, Crafting with click is only usable from now.>

to <Sorry, shift crafting is disabled.> This is more understandable.

When player gain a crafting leve.

Change playername : Lv 8 -> 9

to Congratulation, you gain a crafting level. Your crafting level is now level 9.

For max crafting level.

message: Congratulation, you had reached the max crafting level. Your crafting level is now level 50.

**Comment by dyukusi** [comment]
Fixed.
