### ISSUE TITLE
How to add this?

### ISSUE THREAD

**Issue by madtomic** [dyukusi/Bukkit_plugins#14]
How can I add this into CraftingItem.java?

(int) (material_info.get_success_rate(pinfo.get_level()) \* 100)

I know this is from GainExperience.java.

After player reached max level. They no longer get the success_rate. Is there a way to show this in every crafting attempt?

**Comment by madtomic** [comment]
![cluntitled](https://cloud.githubusercontent.com/assets/6004542/9322514/426dc24c-4542-11e5-9749-a6a1c46264b3.png)

As you can see. when player is max level. They just get one message. I'd like to show the success_rate still.

**Comment by dyukusi** [comment]
Thanks for reporting.
Fixed
