### ISSUE TITLE
crafting level exp

### ISSUE THREAD

**Issue by madtomic** [dyukusi/Bukkit_plugins#16]
![craftlevel error](https://cloud.githubusercontent.com/assets/6004542/9570570/57154592-4f5d-11e5-8702-8efc8fc23b51.png)

![craftlevel error2](https://cloud.githubusercontent.com/assets/6004542/9570591/e7b79910-4f5d-11e5-90db-cf359d3cb0db.png)

As you can see in screenshots.  All the unused exp is carryover to next levels when the player attempt another crafting. Also, it would use up the remaining exp toward next crafting level. Is this intended or it can be changed?

**Comment by dyukusi** [comment]
Thanks for reporting.
Fixed
